require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-md

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
