require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-md

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/*_spec.rb

RSpec/ContextWording:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Lint/MissingSuper:
  Exclude:
    - app/services/*.rb
