require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-md
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - app/models/concerns/*.rb

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - spec/acceptance/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/*_spec.rb
    - spec/requests/api/*_spec.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/*_spec.rb

RSpec/ContextWording:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/SubjectStub:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/services/*.rb
